### PR TITLE
Model Variable Naming Sprint: Part 5

### PR DESCRIPTION
**Pull request by ss421**
## Description

Part of https://github.com/JCSDA-internal/oops/issues/2737

Renames the following variables:
- surface_pressure -> air_pressure_at_surface
- height -> height_above_mean_sea_level
- height_levels -> height_above_mean_sea_level_levels
- height_levels_minus_one -> height_above_mean_sea_level_levels_minus_one
- surface_altitude -> height_above_mean_sea_level_at_surface

## Dependencies

build-group=https://github.com/JCSDA-internal/vader/pull/274
build-group=https://github.com/JCSDA-internal/saber/pull/947
build-group=https://github.com/JCSDA-internal/ufo/pull/3476
build-group=https://github.com/JCSDA-internal/ufo-data/pull/449

To be merged with this PR
- [ ] https://github.com/MetOffice/jjtests/pull/47
- [ ] https://github.com/JCSDA-internal/lfric-jedi/pull/906
- [ ] https://github.com/JCSDA-internal/ops-um-jedi/pull/234

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by mikecooke77** [comment]
All I have done is take the code you have already updated and run:
``` bash
python generate_unittest_netcdfs.py
```
This creates all the test files used by opsinputs.  So even if they haven't changed they are recreated which I think is OK.

**Comment by mikecooke77** [comment]
This is now passing locally for me

**Review by ctgh — APPROVED** [review]
The changes look good to me (although the CI is still failing).

**Review by DJDavies2 — APPROVED** [review]

**Comment by yaswant** [comment]
@mikecooke77 - I think you can remove the ready-to-merge workflow from CI.  It appears to confuse many rather than adding any value to the review process.

**Pull request merged**
