### PR TITLE
update to make varfield_clw name consistent with ufo naming convention

### PR DESCRIPTION
**Pull request by brettcandy**
This is a minor update to the expected meta data for Varfield 68 following the ufo naming convention. It is required in JOPA processing for a single obtype (SSMIS)

### CODE REVIEW

**Review by stemiglio — COMMENTED** [review]
Hi Brett, changes look fine, and I have looked in the `068_VarField_clw.nc4` where I can see the `liquidWaterContent` in `OneDVar`. The only thing I could suggest, if it's not too much work, is to run sith with SSMIS and these changes to prove that VAR is happy with them.

**Comment by brettcandy** [comment]
> Hi Brett, changes look fine, and I have looked in the `068_VarField_clw.nc4` where I can see the `liquidWaterContent` in `OneDVar`. The only thing I could suggest, if it's not too much work, is to run sith with SSMIS and these changes to prove that VAR is happy with them.

I have built the change via bbb into an hpc build and then run ssmis sith.
Output is here http://fcm1/cylc-review/taskjobs/frbt?&suite=sith-ssmis-varfieldsupdate&cycles=20210701T1200Z

 The change in varstats compared to using the nightly build is shown below. The new run is on the right. Note a smaller O-B rms fit for channels 12-16 which are the imager channels. This is consistent with using the retrieved clw in each rttov calculation. 

Screenshot 2023-08-17 145340

**Comment by brettcandy** [comment]
I have also added a plot of the clw in the varobs file (for level1) as an additional check

Figure_1

**Review by stemiglio — APPROVED** [review]
Thanks for testing the mods in VAR. Everything looks good.

**Review by orlewis — APPROVED** [review]
Change looks good and thanks for updating the Varfields.md with the details.

**Comment by brettcandy** [comment]
bump: can this be merged please? I want to trial impact in Batch 6

**Comment by brettcandy** [comment]
Grazias

**Pull request merged**
