### PR TITLE
Changes for ufo-2848.

### PR DESCRIPTION
**Pull request by DJDavies2**
This is to be merged alongside https://github.com/JCSDA-internal/ufo/pull/2848 and https://github.com/JCSDA-internal/oops/pull/2212.  These are changes suggested by @wsmigaj.  Test output is here: http://fcm1/cylc-review/taskjobs/frwd?&suite=oops-2212.

## Depends on
- [ ] JCSDA-internal/ufo/pull/2848
- [ ] JCSDA-internal/oops/pull/2212

### CODE REVIEW

**Comment by DJDavies2** [comment]
I don't know what that failure means?

**Comment by yaswant** [comment]
> I don't know what that failure means?

This is an extra level of protection for opsinputs specific - it indicates that you have not set the "ready to merge" label. 

image

**Comment by DJDavies2** [comment]
Okay I have set it.

**Review by mikecooke77 — APPROVED** [review]
Looks good to me

**Review by mo-keithstewart — APPROVED** [review]

**Comment by yaswant** [comment]
I've updated description and removed "ready to merge" label as the dependent PRs are still open.  Please update the label when appropriate.  

⚠️ We need to retest `opsinputs` should there be further changes to dependent branches of `ufo` and `oops`.

**Review by yaswant — APPROVED** [review]

**Review by ctgh — APPROVED** [review]

**Comment by mikecooke77** [comment]
@DJDavies2 I see the associated PRs are now in.  If you are happy for this to be merged please remove the `do not merge` flag.

**Comment by DJDavies2** [comment]
Done.

**Pull request merged**
