### PR TITLE
Add required CX fields for screen obs

### PR DESCRIPTION
**Pull request by ctgh**
Add required CX fields for screen obs. 

Note that, internally, screen obs are referred to as `Surface`. Therefore a new CX namelist has been created: etc/global/cx/screen/Surface.nl

To be merged with:
* MetOffice/sith#298
* MetOffice/jjdocs#121

ctest output: http://fcm1/cylc-review/taskjobs/chthomas/?suite=opsinputs-screenfields

### CODE REVIEW

**Review by mikethurlow — APPROVED** [review]
Looks good to me. Thanks Chris

**Review by ldhawknesssmith — APPROVED** [review]
All looks ok, thanks Chris

**Review by JoanneAWaller — APPROVED** [review]
Looks good. Thanks Chris.

**Comment by ctgh** [comment]
Thanks for your reviews! I am shortly going to add corresponding PRs in sith and jjdocs.

**Review by mikecooke77 — COMMENTED** [review]
Looks good to me. My only question is whether there needs to be individual tests for each cx variable? I think in general there is.

**Comment by ctgh** [comment]
@mikecooke77 Good idea - now added in e511cb8

**Review by mikecooke77 — APPROVED** [review]

**Comment by mikecooke77** [comment]
@ctgh if you are happy for the merge please add the flag and I will commit

**Comment by ctgh** [comment]
@mikecooke77 Thanks, now done. This PR can go in before the ones in sith and jjdocs because there is no KGO testing for screen.

**Pull request merged**
