### PR TITLE
Radar reflectivity

### PR DESCRIPTION
**Pull request by ctgh**
This PR makes various changes to opsinputs to allow radar reflectivity processing:
* Add RadarZ Varobs and CX namelists.
* Update the Varobs and CX writers.
* Add a variety of specific and more general ctests.
* Update the netCDF generation script and add some new netCDF test files.

### Coordinate merge

Please merge at the same time as:
* https://github.com/MetOffice/sith/pull/374
* https://github.com/MetOffice/jjaux/pull/136
* https://github.com/MetOffice/jjdocs/pull/210

### CODE REVIEW

**Review by DJDavies2 — APPROVED** [review]

**Review by PJLevensMO — APPROVED** [review]
Looks good to me, thanks Chris

**Comment by matthewrmshin** [comment]
Is this a coordinate merge with MetOffice/sith#374?

**Comment by matthewrmshin** [comment]
(I'm seeing some sith/malak kgo compare failures for `kgo_glu*` runs with an mo-bundle build with this branch + jjaux PR. Not sure if they are expected or not. I'll attempt to re-run with isolated changes to understand cause.)

**Review by matthewrmshin — APPROVED** [review]
Tested in my environment. Works as expected.

**Pull request merged**
