### PR TITLE
Output bias corrected wind speeds for OceanWinds

### PR DESCRIPTION
**Pull request by james-cotton**
For the ocean surface wind speed observations, we want to output `BiasCorrObsValue/WindSpeed` to the Varobs file instead of the ObsValue. The ctest has been updated accordingly.

### CODE REVIEW

**Comment by adammaycock** [comment]
Presumably this will require sith and malak kgo updates?

**Comment by james-cotton** [comment]
Hi Adam, I haven't added this obtype to SITH yet (in-progress at the moment) so no KGO updates. This is an observation type that hasn't been used operationally so has been a lower priority to port to JOPA.

**Review by mikecooke77 — COMMENTED** [review]
I think the variable should be windSpeed? Is this varfield used for any other obstype?

**Comment by james-cotton** [comment]
That's just a typo in Varfields.md, I will fix that. This varfield has only been used (in recent memory at least) for testing ocean surface (10m) wind speed data e.g. from SMOS, GNSS-R.

**Review by ctgh — APPROVED** [review]

**Review by DJDavies2 — APPROVED** [review]

**Review by mikecooke77 — APPROVED** [review]

**Pull request merged**
