### PR TITLE
Met Office varname (sprint_0)

### PR DESCRIPTION
**Pull request by ss421**
## Description

Update the following variable names:

`m_v` -> `water_vapor_mixing_ratio_wrt_dry_air`
`m_ci` -> `cloud_ice_mixing_ratio_wrt_dry_air`
`m_cl` -> `cloud_liquid_water_mixing_ratio_wrt_dry_air`
`m_r` -> `rain_mixing_ratio_wrt_dry_air`
`m_t` -> `total_water_mixing_ratio_wrt_dry_air`
`relative_humidity_2m` -> `relative_humidity_at_2m`

More details are included in [lfric-jedi issue: 899](https://github.com/JCSDA-internal/lfric-jedi/issues/899)

## Issue(s) addressed

Resolves [#899](https://github.com/JCSDA-internal/lfric-jedi/issues/899)

## Testing

Tested via `mo-bundle`, `sith` and `malak`. Output for all the tests will be collated in https://github.com/JCSDA-internal/lfric-jedi/issues/899

## Dependencies

- [ ] https://github.com/JCSDA-internal/ops-um-jedi/pull/233
- [ ] https://github.com/JCSDA-internal/lfric-jedi/pull/900
- [ ] https://github.com/MetOffice/sith/pull/393
- [ ] https://github.com/MetOffice/malak/pull/195
- [ ] https://github.com/MetOffice/jjdocs/pull/222
- [ ] https://github.com/MetOffice/jjtests/pull/46
- [ ] https://github.com/JCSDA-internal/saber/pull/950
- [ ] https://github.com/JCSDA-internal/vader/pull/275

## Impact

Effects the Met Office model interfaces and workflows only.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by DJDavies2 — APPROVED** [review]

**Review by yaswant — APPROVED** [review]

**Comment by yaswant** [comment]
@matthewrmshin Note the GitHub Action workflows were skipped for this PR. I am not sure why.

**Comment by ss421** [comment]
> @matthewrmshin Note the GitHub Action workflows were skipped for this PR. I am not sure why.

Is it because I dont have `ready to merge` label?:

`This PR does not have 'ready to merge' label.`

I wasn't sure if I should add it yet as this is a coordinated merge.

**Comment by yaswant** [comment]
Ready to Merge is a separate workflow and has correctly failed. But the main CI build-test has not started at all.  Did you have this PR marked as Draft by any chance? Also you could actually use the `build-group=...` syntax in your PR instead of the dependency list?

**Review by matthewrmshin — APPROVED** [review]
Tested in my environment. Works as expected.

**Pull request merged**
